#!/bin/bash

set -o errexit
set -o pipefail

OPTS_SPEC="\
    git gerrit change-ids

This will help you add Change-Ids to your existing commits.  If you have run
'git-gerrit-setup' then Change-Ids will automatically be added for any future
commits in this repo.
--
h,help      show the help
"
eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"

PATH=$PATH:$(git --exec-path)
. git-sh-setup

set -o nounset

require_work_tree

# set GIT_EDITOR=true because we can't --exec without --interactive but we
# don't really want to be --interactive
GIT_EDITOR=true git rebase --interactive \
    --exec "git reset --soft HEAD^ && git commit -C ORIG_HEAD" "$@"
