#!/bin/bash

set -o errexit
set -o pipefail

OPTS_SPEC="\
    git gerrit add-change-ids
--
h,help      show the help
"
eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"

PATH=$PATH:$(git --exec-path)
. git-sh-setup

set -o nounset

require_work_tree

echo "\
Hello
There
   Indent
"
read -s -n 1 -p 'Press any key to continue...' response

git rebase --interactive \
    --exec "git reset --soft HEAD^ && git commit -C ORIG_HEAD"
