#!/bin/bash

main () {
    case "$1" in
        '') help ;;
        -h|--help) help ;;
        change-ids) shift; git-gerrit-change-ids "$@" ;;
        init) shift; git-gerrit-init "$@" ;;
        *) echo "Unknown subcommand: $1" 1>&2 ; exit 128;;
    esac
}

help () {
    echo "usage: git gerrit <subcommand>"
    echo
    echo "Available subcommands are:"
    echo "   init         Initialize repo for use with Gerrit"
    echo "   change-ids   Add required Change-Ids to local commits (before pushing)"
    echo "   push         Push branch for review with options for reviewers, topic, etc."
    echo
    echo "Try 'git gerrit <subcommand> --help' for details."
}

main "$@"
